$(document).ready(function(){
     $('.edit-trigger').click(function(){
        $('#edit-modal').modal('show');
     });
     $('#cancel').click(function(){
        $('#edit-modal').modal('hide');
     });
       $('.delete-trigger').click(function(){
        $('#delete-modal').modal('show');
     });
});
